sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: xxxx
    password: xxxx
  alioss:
    bucket-name: xxxx
    endpoint:   xxxxx

    access-key-secret: xxxx
    access-key-id: xxxxx
  wechat:
    appid: xxxx
    secret: xxxx