sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: xxxxxxx
    port: xxxx
    database: xxx
    username: xxxxx
    password: xxxxxx
  alioss:
    bucket-name:xxxxxxx
    endpoint:   xxxx

    access-key-secret: xx
    access-key-id: xxxx
  wechat:
    appid: xxx
    secret: xxx